parameters:
  xlcloud_defaultKeyName: xyz
  xlcloud_defaultInstanceType: m1.small 
  xlcloud_defaultImageId: F19-x86_64-xlcloud
  xlcloud_defaultSubnetId: xyz
  xlcloud_brokerAddress:
  xlcloud_brokerUsername: xlcloud 
  xlcloud_brokerPassword": xlcloud 
  xlcloud_brokerPort: 63613

resource_registry:
    XLCLOUD::Layer::GettingStarted: file:///Users/Patrick/Workspace/heat-resources-ci/templates/layer-blueprints/getting-started-layer.template
