Description: XLcloud HPC Virtual Cluster
HeatTemplateFormatVersion: '2012-12-12'
Outputs:
  "xlcloud:xsaIp":
    Description: "XSA endpoint"
    Value: {'Fn::GetAtt': ['Slurm', 'Outputs.xsaIp']}
  "xlcloud:xsaAddress":
    Description: "XSA URL"
    Value: {'Fn::Join': ['', ['http://', {'Fn::GetAtt': ['Slurm', 'Outputs.xsaIp']}, ':8080/xsa']]}
  LoginIP:
    Description: "Public address of the login node"
    Value: {'Fn::GetAtt': ['Slurm', 'Outputs.LoginAddress']}
  MonitorURL:
    Description: "Public URL of the monitoring node"
    Value: {'Fn::GetAtt': ['Monitor', 'Outputs.PublicURL']}

Parameters:
  "MonitorPort":
    Default: '8649'
    Type: String
    Description: TCP port of monitoring traffic data

  "xlcloud:Computes:size":
    Description: "Number of compute nodes to launch"
    Type: String
    Default: '2'

  "xlcloud:defaultImageId":
    Type: String
    ConstraintDescription: Must be a valid XLcloud image name.
    AllowedValues: 
    - F19-x86_64-xlcloud
    - CentOS-6.5-x86_64-xlcloud
    Description: Default image name for instances in this stack
    Default: CentOS-6.5-x86_64-xlcloud

  "xlcloud:defaultInstanceType":
    Type: String
    ConstraintDescription: must be a valid XLcloud instance type.
    AllowedValues:
    - m1.tiny
    - m1.small
    - m1.medium
    - m1.large
    - m1.xlarge
    Description: Default instance type (flavor) for instances in this stack
    Default: m1.small

  "xlcloud:defaultKeyName":
    Type: String
    Description: Name of an existing EC2 KeyPair to enable SSH access

  "xlcloud:Computes:size":
    Description: "Number of compute nodes to launch"
    Type: String
    Default: '2'

  "xlcloud:brokerAddress":
      Type: "String"
      Description: "RabbitMQ broker address"

  "xlcloud:brokerPort":
      Type: "String"
      Description: "RabbitMQ broker port"
      Default: '63613'

  "xlcloud:brokerUsername":
      Type: "String"
      Description: "RabbitMQ broker username"
      Default: 'xlcloud'

  "xlcloud:brokerPassword":
      Type: "String"
      Description: "RabbitMQ broker password"
      Default: 'xlcloud'

  "xlcloud:monitoringCluster":
      Type: "String"
      Description: "Name of the cluster in the monitoring system"
      AllowedPattern: '[a-z|A-Z|0-9]*'
      Default: 'SLURM'

  "xlcloud:stackSecret":
      Description: "Secret for service authentication"
      Type: "String"
      NoEcho: "TRUE"

  "xlcloud:xmsAddress":
      Description: "Address of XLCloud Management System"
      Type: "String"

Resources:
  Slurm:
    Type: AWS::CloudFormation::Stack
    DependsOn: Monitor
    Properties:
      Parameters: {
                    'xlcloud:defaultKeyName' : {Ref: 'xlcloud:defaultKeyName'},
                    'xlcloud:defaultImageId' : {Ref: 'xlcloud:defaultImageId'},
                    'xlcloud:defaultInstanceType' : {Ref: 'xlcloud:defaultInstanceType'},
                    'xlcloud:brokerAddress' : {Ref: 'xlcloud:brokerAddress'},
                    'xlcloud:brokerPort' : {Ref: 'xlcloud:brokerPort'},
                    'xlcloud:brokerUsername' : {Ref: 'xlcloud:brokerUsername'},
                    'xlcloud:brokerPassword' : {Ref: 'xlcloud:brokerPassword'},
                    'xlcloud:monitorIP' : {'Fn::GetAtt': ['Monitor', 'Outputs.MonitorIP']},
                    'xlcloud:monitoringCluster': {Ref: 'xlcloud:monitoringCluster'},
                    'xlcloud:stackId' : {Ref: 'AWS::StackId'},
                    'xlcloud:xmsAddress' : {Ref: 'xlcloud:xmsAddress'},
                    'xlcloud:stackSecret' : {Ref: 'xlcloud:stackSecret'},
                    'xlcloud:Computes:size' : {Ref: 'xlcloud:Computes:size'}}
      TemplateURL : 'http://gitorious.ow2.org/xlcloud/heat-resources-ci/blobs/raw/master/templates/layer-blueprints/slurm-layer.yaml'
      TimeoutInMinutes: 40

  Monitor:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters: {
                    'xlcloud:defaultKeyName' : {Ref: 'xlcloud:defaultKeyName'},
                    'xlcloud:defaultImageId' : {Ref: 'xlcloud:defaultImageId'},
                    'xlcloud:defaultInstanceType' : {Ref: 'xlcloud:defaultInstanceType'},
                    'xlcloud:brokerAddress' : {Ref: 'xlcloud:brokerAddress'},
                    'xlcloud:brokerPort' : {Ref: 'xlcloud:brokerPort'},
                    'xlcloud:brokerUsername' : {Ref: 'xlcloud:brokerUsername'},
                    'xlcloud:brokerPassword' : {Ref: 'xlcloud:brokerPassword'},
                    'xlcloud:monitoringCluster': {Ref: 'xlcloud:monitoringCluster'},
                    'xlcloud:stackId' : {Ref: 'AWS::StackId'},
                    'xlcloud:xmsAddress' : {Ref: 'xlcloud:xmsAddress'},
                    'xlcloud:stackSecret' : {Ref: 'xlcloud:stackSecret'},
                    'MonitorPort' : {Ref: MonitorPort}}
      TemplateURL : 'http://gitorious.ow2.org/xlcloud/heat-resources-ci/blobs/raw/master/templates/layer-blueprints/ganglia-f19.yaml'
      TimeoutInMinutes: 5
