HeatTemplateFormatVersion: '2012-12-12'
Outputs:
  NodeIP:
    Description: Ganglia deployment
    Value: 'Hello'
Parameters:
  MonitorPort: {Default: '8649', Type: String, Description: TCP port of monitoring traffic data}
  #RunList: {Default: ganglia, Type: String,
  #  Description: Collection of recipes to execute}
  NodeCountMinimum:
    Description: Minimum numb
    Type: String
    Default: '1'
    AllowedPattern: '[0-9]*'
  NodeCountMaximum:
    Description: Maximum number of nodes to scale up to
    Type: String
    Default: '4'
    AllowedPattern: '[0-9]*'

## XLCLOUD default Params
 # xlcloud:defaultSubnetUuid: 
 #   Type: String
 #   ConstraintDescription: project doesn't have default subnet defined in XLcloud
 #   Description: Project's default subnet identifier
 #   Default: PENDING
 # xlcloud:defaultNetworkUuid: 
 #   Type: String
 #   ConstraintDescription: project doesn't have network defined in XLcloud
 #   Description: Project's network identifier
 #   Default: PENDING
  xlcloud:defaultImageId: 
    Type: String
    ConstraintDescription: must be a valid XLcloud image name.
    AllowedValues: 
    - F17-x86_64
    - F18-x86_64
    - F19-x86_64-chef-solo
    - cirros-0.3.1-x86_64-uec
    Description: Default image name for instances in this stack
    Default: F19-x86_64-chef-solo
  xlcloud:defaultInstanceType: 
    Type: String
    ConstraintDescription: must be a valid XLcloud instance type.
    AllowedValues: 
    - m1.tiny
    - m1.small
    - m1.medium
    - m1.large
    - m1.xlarge
    Description: Default instance type (flavor) for instances in this stack
    Default: m1.small
  xlcloud:defaultKeyName: 
    Type: String
    Description: Name of an existing EC2 KeyPair to enable SSH access

Description: demonstrate deployment of Ganglia in a Virtual Cluster
Resources:
  CfnUser: {Type: 'AWS::IAM::User'}
  MyKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: {Ref: CfnUser}
  
  # used to fetch matadata via cfn-get-metadata
  ClusterMetaData:
    Type: AWS::AutoScaling::LaunchConfiguration
    DependsOn: AppLayer1
    Metadata:
      IpAddresses: {'Fn::GetAtt': ["AppLayer1", "Outputs.NodeIPs"]}
      #IpAddresses: {'Fn::GetAtt': [Layer1, InstanceList]}
    Properties:
      ImageId: foobar
      InstanceType: foobar

  MonitorHandle:
    Type: AWS::CloudFormation::WaitConditionHandle
  MonitorReady:
    Type: AWS::CloudFormation::WaitCondition
    Properties:
      Handle: {Ref: MonitorHandle}
      Count: '1' 
      Timeout: '1600'

  AppLayer1:
    Type: AWS::CloudFormation::Stack
    DependsOn: MonitorReady
    Properties:
      Parameters: { #'MyKeyIam' : {Ref: MyKey}, 
                    'xlcloud:defaultKeyName' : {Ref: 'xlcloud:defaultKeyName'},
                    'xlcloud:defaultImageId' : {Ref: 'xlcloud:defaultImageId'},
                    'xlcloud:defaultInstanceType' : {Ref: 'xlcloud:defaultInstanceType'},
                   # 'MyKeySecretAccessKey' : 'foo',
                    'MonitorPort' : {Ref: MonitorPort},
                    'MonitorIP' : {'Fn::GetAtt': ['MonitorNode', 'Outputs.MonitorIP']},
                    'NodeCountMinimum' : {Ref: NodeCountMinimum},
                    'NodeCountMaximum': {Ref: NodeCountMaximum}}

        #'MyKeySecretAccessKey' : {Fn::GetAtt: [MyKey, SecretAccessKey]}}
      TemplateURL : 'http://10.197.217.62/downloads/tpl/app-with-ganglia-f19.yaml'
      TimeoutInMinutes: 2
  MonitorNode:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters: { #'MyKeyIam' : {Ref: MyKey}, 
                    'xlcloud:defaultKeyName' : {Ref: 'xlcloud:defaultKeyName'},
                    'xlcloud:defaultImageId' : {Ref: 'xlcloud:defaultImageId'},
                    'xlcloud:defaultInstanceType' : {Ref: 'xlcloud:defaultInstanceType'},
                    # give waithandler ref for cfn-signal
                    'MonitorHandle' : {Ref: 'MonitorHandle'},
                    'parentStackID' : {Ref: 'AWS::StackId'},
                    'parentIamAccessyKey' : {Ref: 'MyKey'},
                    'parentIamSecretKey' : {'Fn::GetAtt': ['MyKey', 'SecretAccessKey']},
                    'MonitorPort' : {Ref: MonitorPort},
                    'NodeCountMinimum' : {Ref: NodeCountMinimum},
                    'NodeCountMaximum': {Ref: NodeCountMaximum}}

        #'MyKeySecretAccessKey' : {Fn::GetAtt: [MyKey, SecretAccessKey]}}
      TemplateURL : 'http://10.197.217.62/downloads/tpl/ganglia-f19.yaml'
      TimeoutInMinutes: 2
#"/opt/aws/bin/cfn-signal -e 0 
#{Ref: OsControllerWaitHandle}
 # MonitorWaitHandle:
 #   Type: AWS::CloudFormation::WaitConditionHandle
 # MonitorWaitCondition:
 #   Type: AWS::CloudFormation::WaitCondition
 #   DependsOn: Monitor
 #   Properties:
 #     Handle: {Ref: MonitorWaitHandle}
 #     Count: '1'
 #     Timeout: '600'

