Description: XLcloud Slurm Stack 
HeatTemplateFormatVersion: '2012-12-12'
Outputs:
  NodeIP:
    Description: XLcloud Slurm Stack 
    Value: {'Fn::GetAtt': ['SlurmLayer', 'Outputs.HeadAddress']}

Parameters:
  "MonitorPort":
    Default: '8649'
    Type: String
    Description: TCP port of monitoring traffic data

  "xlcloud:Computes:size":
    Description: "Number of compute nodes to launch"
    Type: String
    Default: '2'

  "xlcloud:defaultSubnetUuid":
    Type: String
    ConstraintDescription: Project doesn't have default subnet defined in XLcloud
    Description: Project's default subnet identifier
    Default: c35b06b4-a7cb-4cc5-8b10-6a2b788ae19

  "xlcloud:defaultNetworkUuid":
    Type: String
    ConstraintDescription: Project doesn't have network defined in XLcloud
    Description: Project's network identifier
    Default: c345f427-e1a6-4bd9-9b0a-a181313a2125

  "xlcloud:defaultImageId":
    Type: String
    ConstraintDescription: Must be a valid XLcloud image name.
    AllowedValues: 
    - F19-x86_64-chef-solo
    - F19-x86_64-chef-solo-snap
    Description: Default image name for instances in this stack
    Default: F19-x86_64-chef-solo-snap

  "xlcloud:defaultInstanceType":
    Type: String
    ConstraintDescription: must be a valid XLcloud instance type.
    AllowedValues: 
    - m1.tiny
    - m1.small
    - m1.medium
    - m1.large
    - m1.xlarge
    Description: Default instance type (flavor) for instances in this stack
    Default: m1.small

  "xlcloud:defaultKeyName":
    Type: String
    Description: Name of an existing EC2 KeyPair to enable SSH access

  "xlcloud:Computes:size":
    Description: "Number of compute nodes to launch"
    Type: String
    Default: '2'

  "xlcloud:brokerAddress":
      Type: "String"
      Description: "Rabbitmq broker address"


Resources:
  CfnUser:
    Type: AWS::IAM::User

  MyKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: {Ref: CfnUser}

  SlurmLayer:
    Type: AWS::CloudFormation::Stack
    DependsOn: MonitorNode
    Properties:
      Parameters: { #'MyKeyIam' : {Ref: MyKey}, 
                    'xlcloud:defaultKeyName' : {Ref: 'xlcloud:defaultKeyName'},
                    'xlcloud:defaultImageId' : {Ref: 'xlcloud:defaultImageId'},
                    'xlcloud:defaultSubnetUuid' : {Ref: 'xlcloud:defaultSubnetUuid'},
                    'xlcloud:defaultInstanceType' : {Ref: 'xlcloud:defaultInstanceType'},
                    'xlcloud:brokerAddress' : {Ref: 'xlcloud:brokerAddress'},
                    'xlcloud:monitorIP' : {'Fn::GetAtt': ['MonitorNode', 'Outputs.MonitorIP']},
                    'xlcloud:Computes:size' : {Ref: 'xlcloud:Computes:size'}}
      TemplateURL : 'http://gitorious.ow2.org/xlcloud/heat-resources-ci/blobs/raw/master/templates/layer-blueprints/slurm-layer.yaml'
      #TemplateURL : 'http://10.197.217.62/downloads/tpl/slurm-layer.yaml'
      TimeoutInMinutes: 10

  MonitorNode:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters: { #'MyKeyIam' : {Ref: MyKey}, 
                    'xlcloud:defaultKeyName' : {Ref: 'xlcloud:defaultKeyName'},
                    'xlcloud:defaultImageId' : {Ref: 'xlcloud:defaultImageId'},
                    'xlcloud:defaultInstanceType' : {Ref: 'xlcloud:defaultInstanceType'},
                    'parentStackID' : {Ref: 'AWS::StackId'},
                    'parentIamAccessyKey' : {Ref: 'MyKey'},
                    'parentIamSecretKey' : {'Fn::GetAtt': ['MyKey', 'SecretAccessKey']},
                    'MonitorPort' : {Ref: MonitorPort}}
      TemplateURL : 'http://gitorious.ow2.org/xlcloud/heat-resources-ci/blobs/raw/master/templates/layer-blueprints/ganglia-f19.yaml'
      #TemplateURL : 'http://10.197.217.62/downloads/tpl/ganglia-f19.yaml'
      TimeoutInMinutes: 5
