Description: XLcloud Slurm Stack 
HeatTemplateFormatVersion: '2012-12-12'
Outputs:
  NodeIP:
    Description: XLcloud Slurm Stack
    Value: {'Fn::GetAtt': ['Slurm', 'Outputs.HeadAddress']}

Parameters:
  "MonitorPort":
    Default: '8649'
    Type: String
    Description: TCP port of monitoring traffic data

  "xlcloud:Computes:size":
    Description: "Number of compute nodes to launch"
    Type: String
    Default: '2'

  "xlcloud:defaultSubnetUuid":
    Type: String
    ConstraintDescription: Project doesn't have default subnet defined in XLcloud
    Description: Project's default subnet identifier
    Default: c35b06b4-a7cb-4cc5-8b10-6a2b788ae19

  "xlcloud:defaultNetworkUuid":
    Type: String
    ConstraintDescription: Project doesn't have network defined in XLcloud
    Description: Project's network identifier
    Default: c345f427-e1a6-4bd9-9b0a-a181313a2125

  "xlcloud:defaultImageId":
    Type: String
    ConstraintDescription: Must be a valid XLcloud image name.
    AllowedValues: 
    - F19-x86_64-xlcloud
    Description: Default image name for instances in this stack
    Default: F19-x86_64-xlcloud

  "xlcloud:defaultInstanceType":
    Type: String
    ConstraintDescription: must be a valid XLcloud instance type.
    AllowedValues: 
    - m1.tiny
    - m1.small
    - m1.medium
    - m1.large
    - m1.xlarge
    Description: Default instance type (flavor) for instances in this stack
    Default: m1.small

  "xlcloud:defaultKeyName":
    Type: String
    Description: Name of an existing EC2 KeyPair to enable SSH access

  "xlcloud:Computes:size":
    Description: "Number of compute nodes to launch"
    Type: String
    Default: '2'

  "xlcloud:brokerAddress":
      Type: "String"
      Description: "Rabbitmq broker address"


Resources:
  Slurm:
    Type: AWS::CloudFormation::Stack
    DependsOn: Monitor
    Properties:
      Parameters: {
                    'xlcloud:defaultKeyName' : {Ref: 'xlcloud:defaultKeyName'},
                    'xlcloud:defaultImageId' : {Ref: 'xlcloud:defaultImageId'},
                    'xlcloud:defaultSubnetUuid' : {Ref: 'xlcloud:defaultSubnetUuid'},
                    'xlcloud:defaultInstanceType' : {Ref: 'xlcloud:defaultInstanceType'},
                    'xlcloud:brokerAddress' : {Ref: 'xlcloud:brokerAddress'},
                    'xlcloud:monitorIP' : {'Fn::GetAtt': ['Monitor', 'Outputs.MonitorIP']},
                    'xlcloud:Computes:size' : {Ref: 'xlcloud:Computes:size'}}
      TemplateURL : 'http://gitorious.ow2.org/xlcloud/heat-resources-ci/blobs/raw/master/templates/layer-blueprints/slurm-layer.yaml'
      TimeoutInMinutes: 20

  Monitor:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters: {
                    'xlcloud:defaultKeyName' : {Ref: 'xlcloud:defaultKeyName'},
                    'xlcloud:defaultImageId' : {Ref: 'xlcloud:defaultImageId'},
                    'xlcloud:defaultInstanceType' : {Ref: 'xlcloud:defaultInstanceType'},
                    'xlcloud:brokerAddress' : {Ref: 'xlcloud:brokerAddress'},
                    'parentStackID' : {Ref: 'AWS::StackId'},
                    'MonitorPort' : {Ref: MonitorPort}}
      TemplateURL : 'http://gitorious.ow2.org/xlcloud/heat-resources-ci/blobs/raw/master/templates/layer-blueprints/ganglia-f19.yaml'
      TimeoutInMinutes: 5
